application:
    image: debian:jessie
    volumes:
        - ./:/var/www/website
    tty: true
db:
    image: mysql
    ports:
        - 33060:3306
    environment:
        MYSQL_DATABASE: website
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 80800:8080
    links:
        - db
c2isapachephp:
    image: c2is/debian-apache2-mod-php5
    environment:
        # Default: website.docker
        WEBSITE_HOST: projectname.loc
        # Default: no, DocumentRoot have not the trailing /web/
        SYMFONY_VHOST_COMPLIANT: "no"
    ports:
        - 800:80
    links:
        - db
    volumes_from:
        - application
